@urlBase = http://localhost:3000/libros
@contentType = application/json

### Obtener todos los libros.
GET {{urlBase}}
Content-Type: {{contentType}}

### Obtener un libro por su id.
GET {{urlBase}}/1
Content-Type: {{contentType}}

### Obtener un libro por parámetros.
GET {{urlBase}}/buscar/titulo
Content-Type: {{contentType}}

### Agregar un libro.
POST {{urlBase}}
Content-Type: {{contentType}}

{
    "title":"Frankenstain",
    "author": "Borges",
    "isbn":9780553212471,
    "category":"CienciaFiccion"
}

### Eliminar un libro.
DELETE {{urlBase}}/1
Content-Type: {{contentType}}

### Actualizar datos de libro.
PUT {{urlBase}}/1
Content-Type: {{contentType}}

{
    "author":"MaryShelly"
}